name: Python Code Quality

on:
  pull_request:
    branches:
      - '*' # Se ejecuta en cualquier rama al hacer un pull request

jobs:
  tareas:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: advanced-security/python-lint-code-scanning-action@v1
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
